// "use client";
import type { Metadata } from "next";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/src/i18n/routing';
import { getTranslations } from "next-intl/server";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(
  {params: {locale}}:{params: {locale:string}}
): Promise<Metadata> {
  const t = await getTranslations({locale, namespace: 'Metadata'});
  return {
    title: t("title"),
    description: t("description"),
  }
}

const theme = createTheme({});

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <head>

      </head>
      <body>
      <NextIntlClientProvider messages={messages}>
        <MantineProvider theme={theme}>
          {children}
        </MantineProvider>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
