name: Dry Build

on:
  pull_request:

jobs:
  dry_build:
    name: Dry Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build